config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Root route
  root 'home#index' # +

  # Static pages
  get 'about', to: 'pages#about', as: 'pages_about' # +
  get 'contact', to: 'pages#contact', as: 'pages_contact' # +

  # Main sections
  get 'epgs', to: 'epgs#index', as: 'epgs' # +
  get 'live', to: 'live#show', as: 'live' # +

  get 'projects', to: 'projects#index', as: 'projects'
  get 'project/:slug', to: 'projects#show', as: 'project'
  get 'project/:slug/episodes', to: 'episodes#index_for_project', as: 'project_episodes' # +

  get 'archive', to: 'episodes#index', as: 'archive' # +
  get 'episode/:episode_id', to: 'episodes#show', as: 'episode' # +

  get 'articles', to: 'articles#index', as: 'articles' # +
  get 'article/:id', to: 'articles#show', as: 'article' # +
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  validates :title, :content, :category, :published, :published_at, :views_count, presence: true
  validates :views_count, numericality: { greater_than_or_equal_to: 0 }
  validates :featured, inclusion: { in: [true, false] }

  enum category: {
    news: 0,
    article: 1,
    video: 2
  }
end

app/models/epg.rb
# frozen_string_literal: true

class Epg < ApplicationRecord
  belongs_to :project
  belongs_to :episode

  validates :start_time, :end_time, presence: true
  validates :project_id, :episode_id, presence: true
end

app/models/episode.rb
# frozen_string_literal: true

class Episode < ApplicationRecord
  belongs_to :project
  has_many :epgs, dependent: :destroy

  validates :title, :description, :duration, :video_url, presence: true
  validates :duration, numericality: { greater_than_or_equal_to: 0 }
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  has_many :episodes, dependent: :destroy
  has_many :epgs, dependent: :destroy

  validates :title, :description, presence: true
  validates :active, inclusion: { in: [true, false] }
  validates :featured, inclusion: { in: [true, false] }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end
end

app/controllers/epgs_controller.rb
# frozen_string_literal: true

class EpgsController < ApplicationController
  def index
    @epgs = Epg.all
  end
end

app/controllers/episodes_controller.rb
# frozen_string_literal: true

class EpisodesController < ApplicationController
  def index; end

  def index_for_project; end

  def show_for_project; end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/live_controller.rb
# frozen_string_literal: true

class LiveController < ApplicationController
  def show; end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def about; end

  def contact; end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  def index; end

  def show; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/archive_helper.rb
# frozen_string_literal: true

module ArchiveHelper
end

app/helpers/episodes_helper.rb
# frozen_string_literal: true

module EpisodesHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/live_helper.rb
# frozen_string_literal: true

module LiveHelper
end

app/helpers/news_helper.rb
# frozen_string_literal: true

module NewsHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/schedule_helper.rb
# frozen_string_literal: true

module ScheduleHelper
end

app/helpers/shows_helper.rb
# frozen_string_literal: true

module ShowsHelper
end

app/views/articles/index.html.erb
<h1 class="page-title">Articles</h1>

<div class="articles">
  <% @articles.each do |article| %>
    <a href="<%= article_path(article) %>" class="article">
      <%= image_tag article.image_url, class: "article__image" %>
      <h2 class="article__title"><%= article.title %></h2>
    </a>
  <% end %>
</div>

app/views/articles/show.html.erb
<h1 class="page-title"><%= @article.title %></h1>
<div class="container">
    <div class="article__content">
        <%= @article.content %>
    </div>
</div>

app/views/articles/tags.html.erb
<h1>Articles Tags</h1>
<p>Find me in app/views/articles/tags.html.erb</p>

app/views/epgs/index.html.erb
<div class="container">
    <h1 class="page-title">EPG</h1>
    <div class="epgs">
        <% if @epgs.any? %>
            <% @epgs.each do |epg| %>
                <div class="epg">
                    <div class="epg__title">
                    <% if epg.start_time %>
                    <%= epg.start_time %>
                <% else %>
                        <p>Без названия</p>
                    <% end %>
                </div>
            <% end %>
        <% else %>
            <p class="epgs__empty">Нет данных</p>
        <% end %>
    </div>
</div>

app/views/episodes/index.html.erb
<h1>Archive</h1>
<p>Find me in app/views/episodes/index.html.erb</p>

app/views/episodes/index_for_project.html.erb
<h1>Episodes for project</h1>
<p> find app\views\episodes\index_for_project.html.erb</p>

app/views/episodes/show.html.erb
<h1>Episodes#show</h1>
<p>Find me in app/views/episodes/show.html.erb</p>

app/views/home/index.html.erb
<div class="container">
    <h1 class="page-title">Homepage</h1>
    <p class="no-content">Пока что ничего нет</p>
</div>

app/views/live/show.html.erb
<script src="https://cdn.jsdelivr.net/npm/hls.js@latest"></script>

<div class="container">
    <h1 class="page-title">Live</h1>
    <div class="live__content">
        <video id="video" width="100%" height="100%" autoplay></video>
    </div>
</div>

<script>
    const video = document.getElementById('video');
    const hls = new Hls();
    hls.loadSource('https://stream.mux.com/v69RSHhFelSm4701snP22dYz2jICy4E4FUyk02rW4gxRM.m3u8');
    hls.attachMedia(video);
    hls.on(Hls.Events.MANIFEST_PARSED, function () {
        video.play();
    });
</script>

app/views/projects/index.html.erb
<h1>Projects</h1>
<p>Find me in app/views/projects/index.html.erb</p>

app/views/projects/show.html.erb
<h1>Projects#show</h1>
<p>Find me in app/views/projects/show.html.erb</p>