config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Root route
  root 'home#index' # +

  # Static pages
  get 'about', to: 'pages#about', as: 'pages_about' # +
  get 'contact', to: 'pages#contact', as: 'pages_contact' # +

  # Main sections
  get 'epgs', to: 'epgs#index', as: 'epgs' # +
  get 'live', to: 'live#show', as: 'live' # +

  get 'projects', to: 'projects#index', as: 'projects'
  get 'project/:slug', to: 'projects#show', as: 'project'
  get 'project/:slug/episodes', to: 'episodes#index_for_project', as: 'project_episodes' # +

  get 'archive', to: 'episodes#index', as: 'archive' # +
  get 'episode/:episode_id', to: 'episodes#show', as: 'episode' # +

  get 'articles', to: 'articles#index', as: 'articles' # +
  get 'article/:id', to: 'articles#show', as: 'article' # +
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  validates :title, :content, :category, :published, :published_at, :views_count, presence: true
  validates :views_count, numericality: { greater_than_or_equal_to: 0 }
  validates :featured, inclusion: { in: [true, false] }

  enum category: {
    news: 0,
    article: 1,
    video: 2
  }
end

app/models/epg.rb
# frozen_string_literal: true

class Epg < ApplicationRecord
  belongs_to :project
  belongs_to :episode

  validates :start_time, :end_time, presence: true
  validates :project_id, :episode_id, presence: true
end

app/models/episode.rb
# frozen_string_literal: true

class Episode < ApplicationRecord
  belongs_to :project
  has_many :epgs, dependent: :destroy

  validates :title, :description, :duration, :video_url, presence: true
  validates :duration, numericality: { greater_than_or_equal_to: 0 }
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  has_many :episodes, dependent: :destroy
  has_many :epgs, dependent: :destroy

  validates :title, :description, presence: true
  validates :active, inclusion: { in: [true, false] }
  validates :featured, inclusion: { in: [true, false] }
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end
end

app/controllers/epgs_controller.rb
# frozen_string_literal: true

class EpgsController < ApplicationController
  def index
    @epgs = Epg.all
  end
end

app/controllers/episodes_controller.rb
# frozen_string_literal: true

class EpisodesController < ApplicationController
  def index; end

  def index_for_project; end

  def show_for_project; end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/live_controller.rb
# frozen_string_literal: true

class LiveController < ApplicationController
  def show; end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def about; end

  def contact; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/archive_helper.rb
# frozen_string_literal: true

module ArchiveHelper
end

app/helpers/episodes_helper.rb
# frozen_string_literal: true

module EpisodesHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/live_helper.rb
# frozen_string_literal: true

module LiveHelper
end

app/helpers/news_helper.rb
# frozen_string_literal: true

module NewsHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/schedule_helper.rb
# frozen_string_literal: true

module ScheduleHelper
end

app/helpers/shows_helper.rb
# frozen_string_literal: true

module ShowsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="kk">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) + " | INSPORT TV" : "INSPORT TV" %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload" %>
    
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
    
    <%= yield :head if content_for?(:head) %>
  </head>

  <body>
    <header class="header">
      <div class="container header__inner">
        <%= link_to "InsportTV", root_path, class: "logo" %>
        
        <nav class="nav">
          <%= link_to "Прямой эфир", live_path, class: "nav__link" %>
          <%= link_to "Программа", epgs_path, class: "nav__link" %>
          <%# <%= link_to "Новости", articles_path, class: "nav__link" %>
          <%# <%= link_to "Передачи", projects_path, class: "nav__link" %>
          <%# <%= link_to "Архив", archive_path, class: "nav__link" %>
        </nav>
      </div>
    </header>

    <main class="main">
      <div class="container">
        <%= yield %>
      </div>
    </main>
    <footer class="footer">
      <div class="container">
        <div class="footer__grid">
          <div>
            <p class="footer__title">О нас</p>
            <p>Казахстанский спортивный телеканал</p>
          </div>
          <div class="footer__links">
            <p class="footer__title">Ссылки</p>
            <ul>
              <li><%= link_to "Контакты", pages_contact_path %></li>
              <li><%= link_to "О нас", pages_about_path %></li>
            </ul>
          </div>
          <div>
            <p class="footer__title">Контакты</p>
            <p>info@insport.tv</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>